### ISSUE TITLE
Biomes O Plenty's Bayou underwater fog color is very odd.

### ISSUE THREAD

**Issue by MagmaSlime123** [Fuzss/fivefeetsmall#101]
Title. Happens with/without other mods. Other swamp-like biomes may also have weird colors, but I have not tested.

![2022-08-05_13 33 22](https://user-images.githubusercontent.com/51277766/183148648-0f0a9c18-f970-4111-9618-9c7de28a577c.png)

**Comment by embeddedt** [comment]
Thanks, should be fixed in 1.14.4.
