### ISSUE TITLE
[Question] Any plans to backport at least the swimming mechanic back to 1.7.10?

### ISSUE THREAD

**Issue by Desempregago** [Fuzss/fivefeetsmall#103]
Smart Moving glitches custom armor, so I can't use it

**Comment by embeddedt** [comment]
A swimming backport is not planned at the moment. 1.7.10 handles player positioning and movement quite differently from 1.8+ so the mod would need some substantial changes. I don't have the time for that currently.

Backporting the water color is possible in the future but it would likely be contributed to Et Futurum Requiem.
