### ISSUE TITLE
Like #101, BoP's Dead Swamp also has no set water fog color.

### ISSUE THREAD

**Issue by MagmaSlime123** [Fuzss/fivefeetsmall#104]
Title.

![2022-09-08_22 22 37](https://user-images.githubusercontent.com/51277766/189271648-f789df35-04e6-4953-b750-f60dd010dae6.png)

**Comment by embeddedt** [comment]
It is set to the same color they chose for BoP 1.15.2, the last version to include the biome (under the name Mire).

![2023-12-30_12 53 59](https://github.com/embeddedt/aquaacrobatics/assets/42941056/0cfc4e9b-41f5-44b1-abca-b348d9d4d618)

The color in Aqua Acrobatics is the second hex value [here](https://github.com/embeddedt/aquaacrobatics/blob/8993e6e20671abf75e0b059c5d877d7116924fa6/src/main/java/com/fuzs/aquaacrobatics/biome/BiomeWaterFogColors.java#L31), and BoP passes the same value to `waterFogColor` [here](https://github.com/Glitchfiend/BiomesOPlenty/blob/fab38c4c3527dffebd8d67cf49a5e809280ffb94/src/main/java/biomesoplenty/common/biome/overworld/MireBiome.java#L42).
