### ISSUE TITLE
Player is unusually bouyant

### ISSUE THREAD

**Issue by brisingraerowing** [Fuzss/fivefeetsmall#106]
When in water the player will constantly float up, which is somewhat annoying when working underwater. I've done some testing, but haven't figured out if this is related to a config option or not.

**Comment by embeddedt** [comment]
This does not appear to occur with only Aqua Acrobatics installed from some quick testing.

As an educated guess, do you happen to have Better Diving installed too? I am not sure if it even works without conflicts but I recall it having some buoyancy like this.

**Comment by embeddedt** [comment]
Is this still an issue?
