### ISSUE TITLE
Crash (client) 1.12.2

### ISSUE THREAD

**Issue by SeagalKru** [Fuzss/fivefeetsmall#107]
(Google Translate)

Hello!
I decided to install your mod in my assembly and now the client crashes the game.
Crash log attached.
Thank you!

[crash-2022-11-12_12.05.43-client.txt](https://github.com/Fuzss/aquaacrobatics/files/9994586/crash-2022-11-12_12.05.43-client.txt)

**Comment by embeddedt** [comment]
Try installing MixinBooter as well.

**Comment by SeagalKru** [comment]
There are no problems with this: it was installed automatically immediately after the main mod. It's in the mod list.

**Comment by embeddedt** [comment]
Hmm, it doesn't seem to be listed in the mod list in your crash report. Are you sure?

**Comment by SeagalKru** [comment]
![image](https://user-images.githubusercontent.com/46864165/201483287-0babf712-3e44-40a5-a25e-4cb95829e026.png)

**Comment by embeddedt** [comment]
MixinBooter and MixinBootstrap are not the same thing.

**Comment by SeagalKru** [comment]
In the crash log file, the line "33", in which this mod is indicated:
"java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader"

**Comment by SeagalKru** [comment]
Wow!!!!

**Comment by embeddedt** [comment]
There are several mods which provide slightly different implementations of Mixin. Please install [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) and see if the issue persists.

**Comment by SeagalKru** [comment]
It had to be installed separately. I'm going to try now.

**Comment by SeagalKru** [comment]
It seems like the game is loading without crash.
1 question: do these 3 mods need to be installed on the server or are they exclusively for the client?

**Comment by embeddedt** [comment]
They should be installed on both the server and client.

**Comment by SeagalKru** [comment]
OK I understood.

So, the client has loaded, everything is fine.
I'll try to play, if anything - let me know.

I was inattentive to the crash information: I read the first half of the mod's name, but didn't look at the second half. I sincerely apologize for wasting your time!

**Comment by embeddedt** [comment]
No problem; glad you got it fixed. :slightly_smiling_face:
