### ISSUE TITLE
Incompatibility with Tick Central (Library mod for Lag Goggles)

### ISSUE THREAD

**Issue by Delfite** [Fuzss/fivefeetsmall#109]
### **Relevant Attachments**
Latest.log: https://mclo.gs/kkcqtLM
Incompatible mod(s): [Tick Central](https://www.curseforge.com/minecraft/mc-mods/tickcentral/)

### **Description**
For some reason Tick Central doesn't play nice with Aqua Acrobatics. Not sure if a third mod could be causing this issue but removing Tick Central seems to have fixed the crash. For some reason the library itself has duplicate class file signatures for `net/minecraft/block/BlockSoulSand` when it probably shouldn't >_>

This truly is a bruh moment. Oh well!

**Comment by embeddedt** [comment]
Known issue, please use the workaround [here](https://github.com/embeddedt/aquaacrobatics/issues/44#issuecomment-1002681548).
