### ISSUE TITLE
back equipment not in correct position

### ISSUE THREAD

**Issue by touhouzun** [Fuzss/fivefeetsmall#11]
Five Feet Small:
![2021-01-01_13 25 26](https://user-images.githubusercontent.com/31458903/103434132-f1e28a80-4c37-11eb-9e6d-fe7550af76df.png)
![2021-01-01_13 25 39](https://user-images.githubusercontent.com/31458903/103434134-f4dd7b00-4c37-11eb-9177-a60b4f243a47.png)
![2021-01-01_13 25 52](https://user-images.githubusercontent.com/31458903/103434135-f60ea800-4c37-11eb-84fe-014390a5c20c.png)
Aqua Acrobatics, without shift:
![2021-01-01_13 32 53](https://user-images.githubusercontent.com/31458903/103434162-5ef62000-4c38-11eb-9bea-184b8b75c182.png)
![2021-01-01_13 33 07](https://user-images.githubusercontent.com/31458903/103434163-60bfe380-4c38-11eb-8050-15547968c1f9.png)
![2021-01-01_13 33 37](https://user-images.githubusercontent.com/31458903/103434165-61f11080-4c38-11eb-9505-a5bcf6245507.png)
Aqua Acrobatics, with shift:
![2021-01-01_13 32 55](https://user-images.githubusercontent.com/31458903/103434172-8d73fb00-4c38-11eb-9f1b-bd9712a640f7.png)
![2021-01-01_13 33 11](https://user-images.githubusercontent.com/31458903/103434173-8fd65500-4c38-11eb-8a40-5d917c6a8755.png)
![2021-01-01_13 33 40](https://user-images.githubusercontent.com/31458903/103434174-91078200-4c38-11eb-8bc8-2d86b563657b.png)
mods used:
![捕获](https://user-images.githubusercontent.com/31458903/103434198-e04db280-4c38-11eb-915f-0194d319866c.PNG)

**Comment by Fuzss** [comment]
Fixed in d511588 and released on CurseForge as v1.1.5.
Thanks for being such an active bug reporter!
