### ISSUE TITLE
[CRASH} Falling with Elytra looking straight up. (Video Attached)

### ISSUE THREAD

**Issue by marvinspower1** [Fuzss/fivefeetsmall#114]
There is a serious issue with the elytra where when looking straight up while gliding down to ground the game crashes. It does it no matter what I do. I tried changing the config to the mod but nothing helps. I even changed the gamerule with elytra check. Nothing seems to fix it. I have no other movement mod so I don't understand what could be causing this. Please help!

I love this mod and don't want to lose it. 
Here is a short video of me showing the glitch below.
https://user-images.githubusercontent.com/128395444/226379646-e09feacb-aa97-4854-abb8-7a442ae32062.mp4

**Comment by embeddedt** [comment]
Please send the latest.log file when the crash happens.

**Comment by embeddedt** [comment]
Cannot reproduce with just Aqua Acrobatics installed, so without more information I'm unable to fix this unfortunately.
