### ISSUE TITLE
Tropicraft overrides crouch height

### ISSUE THREAD

**Issue by Invadermonky** [Fuzss/fivefeetsmall#116]
Incompatibility found when running this mod with Tropicraft. [](https://www.curseforge.com/minecraft/mc-mods/tropicraft/)

Tropicraft appears to override the crouch height causing it to revert to the normal 1.12 height. Spamming crouch will cause the camera to sometimes drop to the Aqua Acrobatics height before snapping up.

I have no idea if you can even fix this issue, but I figured I would let you know that it does exist.

**Steps to Reproduce:**
1. Install both Aqua Acrobatics and Tropicraft.
2. Attempt to crouch.

**Comment by embeddedt** [comment]
Hi, this can be fixed by disabling `enableSwimAnimation` in `tropicraft.cfg`.
