### ISSUE TITLE
Conflict with ProjectE in spectator mode

### ISSUE THREAD

**Issue by xJon** [Fuzss/fivefeetsmall#117]
> if you are wearing Gem leggings (the gravity greaves) and you enter spectator mode as soon as you go through a wall you fall below bedrock at -1 or -2 and you cant get back up without tping out.

(from https://github.com/xJon/Tekkit-2/issues/175, resolved by removing Aqua Acrobatics, reproducible with just ProjectE + Aqua Acrobatics)

**Comment by embeddedt** [comment]
Fixed in 1.15.3.
