### ISSUE TITLE
Screen shaking when lunging with Tinker's Construct Longsword

### ISSUE THREAD

**Issue by notmucht0it** [Fuzss/fivefeetsmall#118]
The problem occurs after about 20 lungs with the longsword. The screen then starts to violently shake until you start swimming. Sprinting can sometimes fix the issue, but swimming seems to be more reliable.

**Comment by Dakotaraptor** [comment]
Just wanted to note I'm having this issue as well

**Comment by embeddedt** [comment]
Can this be reproduced with version 1.15.3? I tried and couldn't get it to happen.
