### ISSUE TITLE
Broken integration with Witchery:Resurrected

### ISSUE THREAD

**Issue by NaCa1814** [Fuzss/fivefeetsmall#119]
### Mod Version
Aqua Acrobatics:1.15.2
Witchery:Resurrected:base-0.6.0-all,infusions-0.6.0(Get from the official Discord channel)

### Crash-Reports
[crash-2023-04-06_13.30.42-client.txt](https://github.com/embeddedt/aquaacrobatics/files/11166817/crash-2023-04-06_13.30.42-client.txt)

### Solution
The safest solution for now is to change the config in aquaacrobatics.cfg to disable the integration with witchery or change the version of witchery from 0.6.0 back to 0.5.2Hotfix4

**Comment by MsRandom** [comment]
Witchery: Resurrected 0.6 is not yet released to the public, and the module that Aqua Acrobatics' compat is built against is not even released to the beta channels, so this should probably be closed for now.
