### ISSUE TITLE
swimming animation still aren't correct

### ISSUE THREAD

**Issue by touhouzun** [Fuzss/fivefeetsmall#12]
![2021-01-01_13 43 08](https://user-images.githubusercontent.com/31458903/103434220-3f132c00-4c39-11eb-8f5a-6e006c5106b2.png)
![2021-01-01_13 43 50](https://user-images.githubusercontent.com/31458903/103434221-49352a80-4c39-11eb-925d-63b884bbc4a3.png)
![2021-01-01_13 46 06](https://user-images.githubusercontent.com/31458903/103434224-4cc8b180-4c39-11eb-86cb-1ef8135d73c0.png)
![2021-01-01_13 46 10](https://user-images.githubusercontent.com/31458903/103434226-50f4cf00-4c39-11eb-89f7-176344696406.png)
![2021-01-01_13 46 24](https://user-images.githubusercontent.com/31458903/103434230-54885600-4c39-11eb-9569-eeb02bbb2999.png)
![2021-01-01_13 46 30](https://user-images.githubusercontent.com/31458903/103434232-594d0a00-4c39-11eb-8123-80373309714e.png)
![捕获](https://user-images.githubusercontent.com/31458903/103434245-7aadf600-4c39-11eb-997c-44dfed081f85.PNG)
It seems that the player's arms rotate an inner 180°, that hurts.

**Comment by Fuzss** [comment]
Fixed in dd9fcd7 and released as v1.2 on CurseForge. Was an incompatibility with Quark.
