### ISSUE TITLE
Removing color from water

### ISSUE THREAD

**Issue by DanielMCP25** [Fuzss/fivefeetsmall#125]
I don't like the white color of the water that the mod has, how do I make it so it can have the standard color and texture of my texture pack?

**Comment by embeddedt** [comment]
There is a config option to disable new water colours.

**Comment by DanielMCP25** [comment]
where is it? i can't find it

**Comment by DanielMCP25** [comment]
![image](https://github.com/embeddedt/aquaacrobatics/assets/135277240/6ce3dc65-4257-405a-8cd1-3cb53b0bdc84)
Here?

**Comment by embeddedt** [comment]
Yes, change "New Water" to false.
