### ISSUE TITLE
Crash with thermal expansion after creating a world for 10-ish seconds

### ISSUE THREAD

**Issue by Xplodin** [Fuzss/fivefeetsmall#127]
https://gist.github.com/Xplodin/c54deffce4ff71105c4d8e7957184a56

im not entirely sure if its thermal or aqua acrobatics but it mentions the two.
feel free to close if its not related

**Comment by embeddedt** [comment]
Try downgrading MixinBooter to 7.1

**Comment by Xplodin** [comment]
Will definitely try that, thank you for the response. Its been giving me a headache all day and ive barely narrowed it down to a few mixin mods. someone with the same issue had censoredasm causing it but I dont have censoredasm installed but they do similar things like mixinbooter

**Comment by Xplodin** [comment]
That did it! sorry about that pinning it on aqua.

**Comment by embeddedt** [comment]
I'm told DupeFix Project conflicts with MixinBooter 8, and removing that would also solve the issue.
