### ISSUE TITLE
Startup Crash with LittleTiles 1.5.76 (1.12.2)

### ISSUE THREAD

**Issue by brisingraerowing** [Fuzss/fivefeetsmall#128]
[Game Output](https://gist.github.com/brisingraerowing/bb27082277efe751945929d4558f048f)

Reverting to LT 1.5.75 prevents the crash.

**Comment by brisingraerowing** [comment]
Further investigation seems to show that these errors are somewhat random, and commonly occur after updating / adding / removing mods.

**Comment by embeddedt** [comment]
Try with MixinBooter 7.1 instead of 8?

**Comment by brisingraerowing** [comment]
I have several other mods that require MixinBooter 8.

**Comment by embeddedt** [comment]
If the error is random I'm not sure that AA is the culprit.

**Comment by brisingraerowing** [comment]
I honestly have no idea who to blame for this. I'll continue investigating.

**Comment by embeddedt** [comment]
There seems to be a stream of random transformer errors going around on 1.12 at the moment, which makes me suspicious it's something about MixinBooter 8 - but like you, I am also unsure what the exact issue really is.
