### ISSUE TITLE
Issues with resizing mod, flatness

### ISSUE THREAD

**Issue by Hydraheads** [Fuzss/fivefeetsmall#13]
For some reason, when you add artemis lib, swimming in the water halves your width in that mod, making you a pancake.
https://www.curseforge.com/minecraft/mc-mods/artemislib

**Comment by Fuzss** [comment]
There is a config option for that in Aqua Acrobatics under ```compat```. It's disabled by default as it conflicts with a lot of mods probably, so far I've noticed Mo' Bends. I can't do much more about it, the core issue lies with ArtemisLib (just fly with an elytra when using growth or shrinking potions from the Resizing Potion mod)
