### ISSUE TITLE
AquaAcrobatics not compatible with latest Essentials Mod Update

### ISSUE THREAD

**Issue by BeetleeJuiicee** [Fuzss/fivefeetsmall#132]
I have been playing a Modpack for a few weeks with the AquaAcrobatics mod in it alongside the Essentials mod so i can play with a friend and just recently today Essentials had an update and after the update Minecraft would crash after pressing play. I looked into the logs and found AquaAcrobatics was the problem and was conflicting with Essentials.
[launcher_log.txt](https://github.com/embeddedt/aquaacrobatics/files/13727203/launcher_log.txt)

**Comment by embeddedt** [comment]
Essential hacks in to the game too much and is known to cause random issues with mods. I'll accept a contribution that fixes this but probably won't be fixing it myself.
