### ISSUE TITLE
Crash with Censoredasm

### ISSUE THREAD

**Issue by iiDogez** [Fuzss/fivefeetsmall#141]
https://pastebin.com/KVdFwt7a latest.log
crash happened right at startup
only using Censoredasm and Aquaacrobatics
latest version, forge 14.23.5.2860

**Comment by embeddedt** [comment]
CensoredASM needs [MixinBooter](https://legacy.curseforge.com/minecraft/mc-mods/mixin-booter) to be installed; this isn't an AA bug.
