### ISSUE TITLE
MultiServer Issues (myte926)

### ISSUE THREAD

**Issue by exlgx** [Fuzss/fivefeetsmall#150]
It's myte926, as you kindly answered, I asked the server and they said that the server can't install mode, but only plugin, do you have a plugin version or are you thinking of releasing it?

**Comment by embeddedt** [comment]
I have no plans to make a plugin version; it would be a lot of effort and isn't worth the time. The effort would be better spent having the server upgrade to *any* Minecraft version after 1.12 (all of which have swimming natively).
