### ISSUE TITLE
[1.12.2] Conflict with Galacticraft. Sneaking under blocks doesn't seem work as they should.

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/fivefeetsmall#16]
Refer'd Issue:
https://github.com/TeamGalacticraft/Galacticraft/issues/17

Minecraft: 1.12.2
Forge: v14.23.5.2854

Mods: 6
[___MixinCompat-0.8___]
AquaAcrobatics-v1.2.4-1.12.2
GalacticraftCore-1.12.2-4.0.2.281
Galacticraft-Planets-1.12.2-4.0.2.281
jei_1.12.2-4.15.0.291
MicdoodleCore-1.12.2-4.0.2.281

It seems you're unable to sneak under upper half-slab blocks correctly if you have Galacticraft installed along with AquaAcrobatics.

You're able to sneak under one half-slab block but after that... you can't sneak under the rest of them unless you aren't holding down the Sneak Key, then you're able to sneak under half-slab blocks although the eye height is kinda inside the half-slab blocks. Though if you wear the Oxygen Mask from Galacticraft then you can no longer sneak under half-slab blocks.

Would compact be needed? Or would I have to go report it to Galacticraft?

P.S.
I dunno if crawling through 1-block gaps is also affected but I don't know how to crawl into those, as I'm kinda new to the mod.

**Comment by Fuzss** [comment]
Thanks for the report! From the looks of it everything is working as expected: Aqua Acrobatics is stopping to resize the player itself when another mod is interfering which Galacticraft is apparently doing. To change this behavior in the case of Galacticraft some compatibility adjustments are needed. Unfortunately Galacticraft is such a giant mod that I wasn't able to locate the relevant code that needs patching. I don't think it's worth the time to work on this, sorry. :(
