### ISSUE TITLE
Random Injection Error on startup

### ISSUE THREAD

**Issue by mo0dss** [Fuzss/fivefeetsmall#17]
Cant load up server or client, even moving the player mixin to clientside stops the server from crashing but now i cant launch my client.

[debug.log](https://github.com/Fuzss/aquaacrobatics/files/5810879/debug.log)
[latest.log](https://github.com/Fuzss/aquaacrobatics/files/5810880/latest.log)

**Comment by Fuzss** [comment]
That's a simple incompatibility with another mod patching EntityPlayer::onUpdate in the exact same spot as Aqua Acrobatics does. Does [this version](https://mega.nz/file/XM0QgSYY#CrXie_hv9GQGHKcxk1wZl2tdKROzflKHmArIZE9uvgk) work better for you?
Also can you please send another log without Aqua Acrobatics? Just the normal one (latest.log).

**Comment by Fuzss** [comment]
Sorry, wrong button.

**Comment by mo0dss** [comment]
The build u sent works perfectly fine.

also here:
[latest.log](https://github.com/Fuzss/aquaacrobatics/files/5826337/latest.log)

**Comment by Fuzss** [comment]
Awesome, thanks!
