### ISSUE TITLE
Black box underwater in 3rd person. 1.12.2 forge 14.23.5.2854

### ISSUE THREAD

**Issue by Sageking10** [Fuzss/fivefeetsmall#19]
this is on the latest version of aqua acrobatics. (1.3.1)
![2021-01-18_17 22 48](https://user-images.githubusercontent.com/48606472/104967807-46b12f80-59b2-11eb-80bc-33932b60312a.png) this was happening way before i installed this mod.

here is my list of mods https://imgur.com/sRiKJai

**Comment by Fuzss** [comment]
That's a vanilla issue. The mod just makes it more apparent as the camera is translated downwards a little more than usual. Fixing this is too much trouble though.
