### ISSUE TITLE
[1.12.2] Conflict with Metallurgy 4 Reforged: Etherium Armor Set doesn't let you phase through walls while sneaking.

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/fivefeetsmall#20]
Minecraft: 1.12.2
Forge: v14.23.5.2854

Mods: 4
[___MixinCompat-0.8___]
AquaAcrobatics-v1.3-1.12.2
jei_1.12.2-4.15.0.291
Metallurgy-4-Reforged-1.2.4

-----

Etherium Armor in Metallurgy allows you to walk through walls if if sneaking while wearing the full set, however if Aqua Acrobatics is installed this causes the set effect to not work correctly. You will be unable to walk through walls as I think it tries to 'push' you outside the block you're in. Also... you view will be blocked as if you were suffocating in a wall which isn't suppose to happen while wearing the set.

**Comment by Fuzss** [comment]
Fixed in v1.3.2.
