### ISSUE TITLE
[1.12.2] Crash with Thicc Entities

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#23]
Mod Versions:
AquaAcrobatics-v1.3.1-1.12.2.jar
thiccentities-1.4.jar

Game won't launch with both mods installed, no given crash report.

**Comment by Fuzss** [comment]
How does [this version](https://mega.nz/file/rElkGYYb#duTnvTIZP7Blz9zTM_kEBoIcPi5l_b8YFlEhWrgseaw) work for you?

**Comment by Fuzss** [comment]
Just did a couple tests and it seems there isn't really a way to fix this. The issue seems to come from both mods patching  `EntityPlayer` class.

**Comment by Lylythii** [comment]
Consider this conflict patched;
- https://github.com/Lylythii/Entifier
- https://www.curseforge.com/minecraft/mc-mods/entifier/files

**Comment by embeddedt** [comment]
Thanks, I've noted this on the mod page.
