### ISSUE TITLE
Artemis Lib Compat not working

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#26]
The compat for artemislib breaks more things than it fixes
![2021-02-03_00 49 12](https://user-images.githubusercontent.com/8508976/106722104-6784a200-65ba-11eb-8e05-6074f0d2c71c.png)
![2021-02-03_00 49 08](https://user-images.githubusercontent.com/8508976/106722108-694e6580-65ba-11eb-89c8-3c70907ac4b1.png)
![2021-02-03_00 48 33](https://user-images.githubusercontent.com/8508976/106722125-6d7a8300-65ba-11eb-80e7-b33072958a11.png)
![2021-02-03_00 48 25](https://user-images.githubusercontent.com/8508976/106722134-6fdcdd00-65ba-11eb-95ae-8c14f8deb3cc.png)

Thankfully turning it off results in only this happening
![2021-02-03_00 53 45](https://user-images.githubusercontent.com/8508976/106722256-969b1380-65ba-11eb-912f-18fd47559974.png)

I know better diving managed to get things working in this area so if you are having trouble getting the compat working you could always look over there. (I don't want to enable both because better diving has some swimming features such as no sinking that I am not a fan of and with this mod it ends up causing the player to autofloat)

I'd love for the hitboxes to work out when tiny cuz it would mean cool little tiles/chisels and bits entrances/exits

**Comment by Fuzss** [comment]
Looks like I forgot a line when refactoring. Fixed in v1.3.3.
