### ISSUE TITLE
Compatibility with BetterDiving

### ISSUE THREAD

**Issue by DoomRater** [Fuzss/fivefeetsmall#31]
BetterDiving has a lot of fun with faster swimming movement, but a couple things break out of the box:
-regardless if BetterDiving's swimming mechanics are enabled or not and regardless of player resize setting on BetterDiving, players no longer resize when swimming.  This might be something on BetterDiving's end.
-When using BetterDiving's swimming mechanics, players are pushed upwards to the surface.  The intended behavior is that players hover.  I am guessing this is BetterDiving's hack to make swimming movement work alongside vanilla.

**Comment by embeddedt** [comment]
I would suggest not using both mods together; Better Diving implements the vast majority of the swimming features itself, and I'm not likely to add compatibility for it at this point as I fear it would simply conflict too much. However, if there's a particular feature from Better Diving that's desirable, I could consider reimplementing it in this mod.

> When using BetterDiving's swimming mechanics, players are pushed upwards to the surface.

Are you referring to swimming or diving? Last time I used the mod, it worked very similarly to 1.13 when diving, although the animation was different.

**Comment by DoomRater** [comment]
Should I decide to use Better Diving in a future mod pack I'll probably find another solution for crawling.

I do think what's happening is that the other mod is trying to make swimming work exactly like it does in Subnautica, where players will hover at the same depth without any input on the keyboard.  I'm pretty sure that's intentional.

Either way thanks for the response.
