### ISSUE TITLE
Elytra helper only seems to affect vanilla elytras

### ISSUE THREAD

**Issue by DoomRater** [Fuzss/fivefeetsmall#34]
The Ender IO Dark Steel Chest with Elytra upgrade and the Thaumic Augmentations Elytra Harness don't get the special elytra handling when it's turned on.  Since multiple mods have an issue, I'm not sure if they need to implement something in order for them to take advantage of the toggle, or if something has been missed in the code here.

**Comment by DoomRater** [comment]
A quick glance at the code suggests the fix is hard coded for vanilla elytras only.  But hand checking armor and baubles for elytra capabilites sounds messy, unless there's some universal sign for elytra wings.

**Comment by embeddedt** [comment]
You're correct. I also encountered this bug but it's not easy to fix without modifying the mods themselves.

The issue for Ender IO is that the vanilla check for `motionY` being less than 0 (which is what Mojang removed in 1.15) is duplicated within their code [here](https://github.com/SleepyTrousers/EnderIO/blob/d6dfb9d3964946ceb9fd72a66a3cff197a51a1fe/enderio-base/src/main/java/crazypants/enderio/base/handler/darksteel/DarkSteelController.java#L228). Aqua Acrobatics patches this out of the vanilla elytra logic but cannot do the same for Ender IO automatically.

I haven't checked Thaumic Augmentations' code but it probably has the same issue.

To fix it for a mod, it either needs to add integration (which won't happen for 1.12 at this point), or I need to patch the mod myself using mixins, which is likely the route I'll end up having to take.

Elytras are so infrequently used in modded that I haven't really considered this a high priority, but if you're still being bothered by it, I can take a look.

**Comment by DoomRater** [comment]
One bit of good news is that Thaumic Augmentation is still in active development, as there is no Thaumcraft for modern Minecraft yet. If you can explain what Codex needs to do, or offer a pull request, he'll likely accept it.

I can't say the same for Ender IO.

**Comment by embeddedt** [comment]
It will be fixed for Ender IO in the next release. Looking at Thaumic Augmentation next.

EDIT: I did read through his code and couldn't find exactly where the elytra is being opened. I'll look again once I finish fixing another issue.

**Comment by embeddedt** [comment]
In 1.10.0 this is fixed for Thaumic Augmentation as well.
