### ISSUE TITLE
[Request]GoProne integration

### ISSUE THREAD

**Issue by DoomRater** [Fuzss/fivefeetsmall#35]
Someone made a mod that allows players to immediately enter crawling mode upon the push of a button.  Looks pretty simple too.  Could we also see that added to Aqua Acrobatics?

**Comment by Nekulian** [comment]
Seeing this get implemented would be nice!
There's a [fork of Ido](https://github.com/Bekos-von-Nimmerland/Ido/tree/1.12.2-with-crawl-on-button) that seems to do something similar,
hopefully this could help with implementing such a feature into Aqua Acrobatics.

**Comment by embeddedt** [comment]
This feature is added in 1.10.0, but is disabled by default since it's not a vanilla feature, and requires the server to also be updated.
