### ISSUE TITLE
¿compatibility with Biomes O' Plenty?

### ISSUE THREAD

**Issue by DeviantSoft** [Fuzss/fivefeetsmall#38]
**AquaAcrobatics-v1.4.0-1.12.2**
-the water color of some biomes is lost with its mod, you could add compatibility with the water color of Biomes O' Plenty.

-I saw an option in your mod = seagrass, ¿you plan to add the generation of coral and seagrass?.

**Comment by embeddedt** [comment]
> I saw an option in your mod = seagrass, ¿you plan to add the generation of coral and seagrass?

Yes, that's a leftover from some experiments I was doing earlier; it has no function right now. I do have plans to add the 1.13 plants eventually (including world generation). In fact, I already have kelp and seagrass mostly working in a private build.

> the water color of some biomes is lost with its mod, you could add compatibility with the water color of Biomes O' Plenty

Which biomes in particular? If you let me know their names I'll try to find the equivalents in the 1.16 version and get the colors from there. The underlying issue there is that 1.12 and 1.13+ need different color values, otherwise the water looks very strange.

**Comment by DeviantSoft** [comment]
Biomes O' Plenty
1. Quagmire
2. Bayou
3. Bog
4. Dead Swamp
5. Mangrove
6. Moor
7. Mystic Grove
8. Ominous Woods
9. Wasteland

these biomes are affected.

although in more current versions of the Biomes O 'Plenty mod some biomes were eliminated or changed.

**Comment by touhouzun** [comment]
AquaAcrobatics-v1.4.0-1.12.2
And well...it's much better to compress two issues into one.
Will there be a little config option to toggle 1.13 water texture&1.13-style fog when underwater true/false?
I'm using fantastic resource packs like this one : https://mizunomcmemo.blogspot.com/
1.13 water texture&1.13-style fog is too blue for me.

**Comment by embeddedt** [comment]
In 1.5.0, I've added custom color support for all biomes except Quagmire, which doesn't seem to exist in any of the modern versions.

> Will there be a little config option to toggle 1.13 water texture&1.13-style fog when underwater true/false?

I looked into this, but toggling the texture doesn't appear to be practical, due to the way Forge works.

**Comment by DeviantSoft** [comment]
Wasteland's water color is the same as Quagmire's. 
you could use it in quarmire

**I will wait anxiously for the algae generation update.**

**Comment by embeddedt** [comment]
> Wasteland's water color is the same as Quagmire's. you could use it in quarmire

Thanks. I will do that in the next update.

**Comment by embeddedt** [comment]
@touhouzun 

> Will there be a little config option to toggle 1.13 water texture&1.13-style fog when underwater true/false?

I found a way of doing this; it will be included in the next release once I have a chance to test it in a modpack.
