### ISSUE TITLE
Replenish Air Slowly slightly bugged?

### ISSUE THREAD

**Issue by Turkey9002** [Fuzss/fivefeetsmall#39]
Just something I noticed while messing around in a world. If you let all the oxygen bubbles go out and then go back up to the surface once you take damage from drowning, it'll replenish your air immediately rather than slowly like it's supposed to be doing.

This doesn't happen when done before running out of air and taking damage.

**Comment by embeddedt** [comment]
Thank you for the report! I've fixed this in 1.5.0.
