### ISSUE TITLE
Newest version crashes on startup

### ISSUE THREAD

**Issue by juraj-hrivnak** [Fuzss/fivefeetsmall#40]
### Issue:
Version 1.4.0 and 1.3.5 crashes on startup _with_ the Mixin Bootstrap mod _installed_.
Removing Mixin Bootstrap or adding Mixin 0.7-0.8 Compatibility didn't help.

### Logs: [latest.log](https://github.com/Fuzss/aquaacrobatics/files/7745788/latest.log)
- Using Forge `14.23.5.2860`

Maybe, reverting the compatibility for Mixin 0.7.0 introduced 1.3.5 could fix this?

**Comment by embeddedt** [comment]
Remove Item Physics; it will almost certainly conflict with the item floating logic included in 1.4.0. Not sure what the issue is with 1.3.5 though.

**Comment by juraj-hrivnak** [comment]
Ahah, yes, that was it! Thank you, the new update is gorgeous! 
Could be a config option to disable the floating logic added, though?

**Comment by embeddedt** [comment]
A config option on its own doesn't help as the mixin gets applied in all cases. What I can do (and have done in 1.5.0) is make it optional so Item Physics will override it. You should be able to add that mod back now.

**Comment by juraj-hrivnak** [comment]
Thank you, this is great!
