### ISSUE TITLE
Duplicate Versions

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#42]
The latest version (1.5) is complaining about duplicate files despite there only being one file for aqua acrobatics.
Here is the log in case it helps: https://gist.github.com/mxnmnm/2aa4a5f3094c0af5e56c083b8f5d651c

**Comment by embeddedt** [comment]
Hmm.. can you try this build?

[mod.zip](https://github.com/Fuzss/aquaacrobatics/files/7766394/mod.zip)

**Comment by mxnmnm** [comment]
Yay that fixed it!

**Comment by embeddedt** [comment]
Thanks, 1.5.1 should be up shortly on CurseForge with the fix.
