### ISSUE TITLE
[Suggestion] Custom biome water colors

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#43]
Would it be possible to add a config where you list a color and a biome to change the biome's water color? It would make it much nicer for people to customize things.

**Comment by embeddedt** [comment]
I've added it, it'll be in the next release. If you want to try it out in the meantime, you can download the nightly build [here](https://github.com/Fuzss/aquaacrobatics/actions/runs/1617644392) (under artifacts).

**Comment by embeddedt** [comment]
Released in 1.5.2.
