### ISSUE TITLE
Missing mixins crash on startup instead of showing a notification screen

### ISSUE THREAD

**Issue by Fuzss** [Fuzss/fivefeetsmall#45]
I had it originally setup so that when mixins are missing the game loads and then shows a notification screen with a download link for mixinbootstrap. Now the game just crashes on startup without providing any information on what went wrong.

I'd really like to see this behavior being reintroduced. I know the code for it is a bit weird and ugly, but the user friendliness part clearly outweighs that, especially since having to install core mod dependencies is not a common thing for a user to have to do on Forge.

**Comment by embeddedt** [comment]
I'll see what I can do. :) I had to tweak some of the coremod logic because the mod was refusing to load correctly when in the dev workspace, which made development a lot harder. However, I should be able to reintroduce this somehow.
