### ISSUE TITLE
Colorless Water in JEI

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#46]
When looking at a recipe that uses water in JEI, the water has no color:
![2021-12-24_03 22 50](https://user-images.githubusercontent.com/8508976/147348718-bfb92c01-4a9f-4930-9977-db422eec625e.png)

**Comment by embeddedt** [comment]
Oh... that's annoying. It's because 1.12 uses a blue texture and 1.13+ uses a white texture. This is also the reason for needing all the biome color overrides.

Thanks for the report; not entirely sure how I'll fix this one.
