### ISSUE TITLE
[1.12.2] Compact with Trinkets & Baubles Race Rings?

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/fivefeetsmall#49]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 4
_MixinBootstrap-1.1.0
AquaAcrobatics-1.5.2
jei_1.12.2-4.16.1.302
Trinkets+and+Baubles-0.31.3

=====

The Race Rings in Trinkets & Baubles can alter the player's size, and while I haven't noticed any major breakage so far, it seems that the hitbox shrinking while sneaking works but it kinda feels like it doesn't affect the size much when you sneak with your normal size. Also... you aren't 'forced' to sneak if you're under a block that you can't fit into so you may end up taking 'inwall' damage from the block above you.

The rings that change your size are... Titan, Fairy, Dwarf, Goblin, Faelis and Dragon. Elf Ring is the same size as the player's size. I'll keep an eye out if any other bugs.

**Comment by embeddedt** [comment]
I've added basic compatibility so Aqua Acrobatics doesn't attempt to control sizing itself if this mod has changed the entity size to anything other than its default. Swimming will still work but the hitbox won't change to reflect it (however, once you're small enough, this doesn't matter anyways). The sneak height will also revert to the vanilla 1.12 style when you are using one of the rings.

I wasn't able to reproduce the block damage issue; can you provide steps on how I can do that?

**Comment by SonicX8000** [comment]
My apologizes but disregard the damage bug, apparently that happens with just Trinkets by itself. Also... alright, still will let you know if something should end up breaking.

EDIT
I completely forget that the Stone of the Sea Trinket changes the way the swimming works if worn, which I dunno if that would cause problems with the 'sprint' swimming. Although there's a config option on trinkets side that disables that enhanced swimming.

**Comment by embeddedt** [comment]
It seems to work great - the player just swims a lot faster. This mod is actually quite interesting; thanks for bringing it to my attention.

**Comment by embeddedt** [comment]
@Z-Tunic Just wanted to let you know that the latest version (1.12.0) should have improved compatibility for this mod; sneak heights and such should now work properly.
