### ISSUE TITLE
crash before launching successfully

### ISSUE THREAD

**Issue by touhouzun** [Fuzss/fivefeetsmall#5]
[latest.log](https://github.com/Fuzss/aquaacrobatics/files/5743974/latest.log)
Sorry for no crash-reports, there's only logs.
Mods used:
![捕获](https://user-images.githubusercontent.com/31458903/103162144-9a06e680-4827-11eb-9cf3-d068138acadf.PNG)
forge 1.12.2-14.23.5.2854
Nsiso Launcher

P.S. successfully launched without both AquaAcrobatics and MixinBootstrap

**Comment by Fuzss** [comment]
Thanks for the report! The ```latest.log``` file is all I need.
Fixed now in 7c52ba7. Crash was caused by incompatibility with wings mod.
