### ISSUE TITLE
Incompatibility with Sledgehammer

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#51]
Tested with mixinbootstrap, sledgehammer, and aqua acrobatics. Looks like mixins are being a big meanie: https://gist.github.com/mxnmnm/90fe24f344bb9204b0f486561ca1f4b4

**Comment by embeddedt** [comment]
`ConcurrentModificationException` is just about impossible to debug, sadly. Does this happen every time you start the game or just sometimes?

**Comment by mxnmnm** [comment]
It happens every time

**Comment by mxnmnm** [comment]
Oh, also version 1.5.1 and before work, but 1.5.2 and after don't work

**Comment by embeddedt** [comment]
This should be fixed in 1.6.2.
