### ISSUE TITLE
Optifine + Aqua Acrobatics makes water grey

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#52]
When both Aqua Acrobatics and Optifine are installed, all water will be grey except with a slight green tint for swamp water regardless of the OF settings. If this can't be fixed by AA (which is likely because, well, Optifine) then I recommend disabling the water coloration by default if Optifine is present. There should at the very least be a config option to disable the water colors.
![2021-12-30_13 03 06](https://user-images.githubusercontent.com/37032857/147711765-8b04e7d2-afce-440d-bdf4-b031092b7f3f.png)

**Comment by embeddedt** [comment]
I think I can fix this one.

**Comment by ghost** [comment]
Awesome. I hope so because I just switched out to this from Idō due to the wings compatibility.

**Comment by embeddedt** [comment]
I've fixed it in 1.6.3. It should be on CurseForge within a couple minutes.

**Comment by embeddedt** [comment]
It's available now.

FYI, unlike other modders, I am willing to work around OptiFine issues where possible.

**Comment by ghost** [comment]
Cool, thanks!
