### ISSUE TITLE
Mods with their own water-rendering blocks don't add color

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#53]
Water is missing color when it's in the sink from cooking for blockheads (tested with 1.6.3) ![2021-12-29_20 12 10](https://user-images.githubusercontent.com/8508976/147721401-3229ebfe-14fa-4516-94f3-81fd3170d4ac.png)

**Comment by embeddedt** [comment]
This also affects Thaumcraft; I'll merge #55 into this so we don't have multiple reports of the same problem at once.

I'm working on a fix (by changing the way textures are handled) but it'll take a bit.

**Comment by embeddedt** [comment]
Fixed in 1.7.0. I've now adjusted the mod to use its own `aquaacrobatics` namespace for the water placed in the world, while still providing a colorized texture under the `minecraft` namespace. This should ensure mods like these which assume the texture has a color continue to work properly.
