### ISSUE TITLE
Compatibility with Openblocks

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#54]
The tank from open blocks does not show water despite having some inside (tested with 1.6.3): ![2021-12-29_20 13 04](https://user-images.githubusercontent.com/8508976/147721482-4a1d0905-f478-4901-b9ba-e5334f3fd5de.png)

**Comment by embeddedt** [comment]
It helps when I don't provide Forge a color that's fully transparent. :laughing: Fixed in 1.7.0.
