### ISSUE TITLE
Water is colorless in the Crucible (Thaumcraft Compatibility)

### ISSUE THREAD

**Issue by Turkey9002** [Fuzss/fivefeetsmall#55]
![2021-12-29_22 51 09](https://user-images.githubusercontent.com/86805568/147722671-f40dc348-98b8-4092-be9f-7bd979e158c6.png)

Interestingly it also affects the particles as well when it's boiled with fire, lava or nitor on the bottom of it.

**Comment by Turkey9002** [comment]
Purifying fluid's colors are affected too oddly enough. I think all modded liquids that have been added in a similar matter to Thaumcraft might have the same side effect. x.x
![2021-12-29_23 02 57](https://user-images.githubusercontent.com/86805568/147723104-3ab64f3a-498a-4181-b777-92fd580b6d1c.png)
![2021-12-29_23 04 17](https://user-images.githubusercontent.com/86805568/147723107-de979825-0c74-4d10-95e0-b8a054425a1a.png)

**Comment by embeddedt** [comment]
Same root cause as #53. Thanks for the report; I'm working on a fix.

**Comment by embeddedt** [comment]
Fixed in 1.7.0.

**Comment by Turkey9002** [comment]
@embeddedt The Crucible oddly doesn't seem to like the fix (not entirely sure if there's other Thaumcraft blocks that uses water like this either)
![2022-08-17_22 09 53](https://user-images.githubusercontent.com/86805568/185285061-9e6e72f7-a539-4572-a163-872407fbf3c4.png)
![2022-08-17_22 11 08](https://user-images.githubusercontent.com/86805568/185285075-fe65d19c-e205-450e-bc8d-91ad617ac94d.png)

**Comment by embeddedt** [comment]
Hmm, possible mod conflict? Do you have Fluidlogged API installed by chance? This is what it looks like in the latest version for me.

![2022-08-18_10 03 57](https://user-images.githubusercontent.com/42941056/185414856-36bbdc4e-75da-4920-9f48-f14e4a328c8a.png)

**Comment by Turkey9002** [comment]
Yup! I've disabled it just now and it now works fine, just seems odd for it to affect the Crucible more specifically.

**Comment by Turkey9002** [comment]
Since Fluidlogged got a major update, I reported it to their side but I was told that it doesn't do anything that would influence colors and textures, and it's more likely an Aqua Acrobatics issue. I think it could be just Thaumcraft being Thaumcraft again when both mods are installed.
