### ISSUE TITLE
Crash on login with latest mod version.

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#57]
Crash report:  https://pastebin.com/NyLYKDXB

Mod worked perfectly for months, but this one will not launch with the current version. 

The game loads fully, but as soon as you try to create a world or join an existing world, it crashes.

**Comment by embeddedt** [comment]
It looks like your version of Trinkets and Baubles is outdated. The latest on CurseForge is 0.31.3, and that is what the integration in Aqua Acrobatics targets.

**Comment by ghost** [comment]
Thank you! Not worth the upgrade, then.

**Comment by embeddedt** [comment]
You can also try disabling the integration in `aquaacrobatics.cfg`, that may fix the issue.
