### ISSUE TITLE
Cyclic Compatibility

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/fivefeetsmall#58]
For some reason the hydrator from cyclic still has white water despite the water seeming to work in a lot of other places. I'm using version 1.7.0
![2021-12-30_22 08 55](https://user-images.githubusercontent.com/8508976/147806677-2eee3ae2-85aa-4fa1-8789-e94f6778f081.png)

**Comment by embeddedt** [comment]
I think this is technically a bug in Cyclic (its fluid renderer doesn't respect the provided color at all), but I have no way of fixing that easily unless it has another 1.12 release. So I've opted to fix it on my end instead.

Thanks for the report, and my apologies for the ugly white water showing up everywhere. I've uploaded 1.7.1 to CurseForge with a fix.
