### ISSUE TITLE
player animation desync with armor when swimming

### ISSUE THREAD

**Issue by touhouzun** [Fuzss/fivefeetsmall#6]
issue with aqua acrobatics and wings installed, tested with various armors
![2020-12-28_20 46 58](https://user-images.githubusercontent.com/31458903/103250754-6c00de00-49b0-11eb-8f4e-ee3c485e78c8.png)
![2020-12-28_20 47 21](https://user-images.githubusercontent.com/31458903/103250759-6efbce80-49b0-11eb-92f9-03d5352b5001.png)
![2020-12-28_20 47 59](https://user-images.githubusercontent.com/31458903/103250761-71f6bf00-49b0-11eb-98d5-9815e8f2a233.png)
![2020-12-28_20 48 16](https://user-images.githubusercontent.com/31458903/103250762-73c08280-49b0-11eb-9a39-7c380eb886d9.png)
![2020-12-28_20 48 56](https://user-images.githubusercontent.com/31458903/103250766-758a4600-49b0-11eb-8ecd-6229679b6cb2.png)

**Comment by Fuzss** [comment]
Fixed in 70d8653 and released on CurseForge as v1.1.3.

Turns out I was using Obfuscate mod all the time while testing which doesn't have this issue.
