### ISSUE TITLE
[1.12.2] No water color if the texture is used with certain mods.

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/fivefeetsmall#60]
Minecraft; 1.12.2
Forge: 14.23.5.2860

Mods: 7* (Varies, depends on the mod that grabs the water textures)
_MixinBootstrap-1.1.0
AquaAcrobatics-1.6.2
Baubles-1.12-1.5.2
Botania+r1.10-362
Chisel-MC1.12.2-1.0.2.45
CTM-MC1.12.2-1.0.2.31
jei_1.12.2-4.16.1.302

-----

![nowatercolortexture](https://user-images.githubusercontent.com/36653806/147893350-1120272b-4e4c-425e-9e17-3e5c3e155bd9.png)
Due to Aqua Acrobatics replacing the water texture with a grey scaled one so it can change color... this affects other mods that use this water texture, such as blocks from Chisel, the water inside a Botania's Petal Apothecary. The water texture for these is supposed to be blue.

These aren't the only listed mods that are affected. The Thermal Expansion's Reservoirs lack a colored water texture when filled with water. I dunno how many other mods are affected by this.

**Comment by embeddedt** [comment]
Please update to the latest version, this should be fixed there.

**Comment by SonicX8000** [comment]
I... should've checked for an update first before opening up an issue in case it was fixed.
![fixedwatercolortexture](https://user-images.githubusercontent.com/36653806/147895470-898cc632-1484-4a47-9d59-a5dd321bc3f9.png)

Looks to be fixed using "AquaAcrobatics-1.7.1". My apologizes.

**Comment by embeddedt** [comment]
No problem. :slightly_smiling_face: I discovered, as you did, that a lot of mods apparently depend on the water texture actually being blue, and don't bother to color it, so I ended up hacking the in-world water to use a different texture that allows recoloring. A side effect of this is that the texture can't be affected by resource packs unless they use the `aquaacrobatics` namespace instead. Also, JourneyMap still shows water in the old color, even though it looks modern when in the world.

**Comment by SonicX8000** [comment]
I didn't know that JourneyMap has a issue with the water colors. Speaking of which... that occurs with Xaero's Minimap/Worldmap as I do recall that the map actually used the updated water colors from Aqua Acrobatics however with the version I'm using right now... it shows the regular non-aqua Acrobatics water colors.

![minimapwatercolor](https://user-images.githubusercontent.com/36653806/147896012-b3546937-83e6-4c0e-9e0f-77690aa1b320.png)
As seen here, the minimap/worldmap is updating to show the water colors. Left side is prob around the time with me using "AquaAcrobatics-1.5.2" and with using "AquaAcrobatics-1.7.1"... the map sees it using the regular water so it's updating to reflect that.

**Comment by embeddedt** [comment]
In the next version after 1.10.0, compatibility will be added for Xaero's and JourneyMap so they display the modern colors again.
