### ISSUE TITLE
Odd graphical bug with the bubble colums feature?

### ISSUE THREAD

**Issue by Carvercarver1** [Fuzss/fivefeetsmall#62]
![2022-01-09_12 20 40](https://user-images.githubusercontent.com/48799631/148684765-d2d2a178-259f-4363-b50c-d7d8c44a20e8.png)

The functions are working, but block itself seems to cause such... thing. Is it specifically my issue, or actual bug?

**Comment by embeddedt** [comment]
I can't reproduce it. Are you using OptiFine? The bubble column block explicitly extends the water block to make sure it renders the same way.

**Comment by Carvercarver1** [comment]
Not really. 
It seems that there is either some conflict or graphical bug I'm not aware of.

**Comment by Carvercarver1** [comment]
Possibly, could be tied to the Streams mod, but I'm not sure.

**Comment by Carvercarver1** [comment]
Did further investigation. It is not Streams mod. 

Also, when in the water, it looks normal, as in, it does not create anything inordinary. It is specifically the top layer of the water texture which is missing, else seems to be there. 
Will check a few options.

**Comment by Carvercarver1** [comment]
So the issue is the FluidLogged mod. It also seems to change the water color a bit.
https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api

**Comment by embeddedt** [comment]
This is fixed in 1.7.2.
