### ISSUE TITLE
Issues with Mekanism Tanks (and Tanks in general)

### ISSUE THREAD

**Issue by Desempregago** [Fuzss/fivefeetsmall#63]
As AA backports 1.3 water colors (you should add a config entry for it), shit breaks
![image](https://user-images.githubusercontent.com/14002834/148838697-9163d2c0-acb6-409d-a1d7-0c34778d23c6.png)

**Comment by embeddedt** [comment]
Which version of Aqua Acrobatics are you using? Most of these issues are resolved in 1.7.1.

**Comment by Desempregago** [comment]
1.6.1

**Comment by Desempregago** [comment]
ah, there was an update? I'll update it then

**Comment by embeddedt** [comment]
Updating will probably solve your issue. :slightly_smiling_face:

**Comment by Desempregago** [comment]
And it did. Thanks for notifying for the update
![image](https://user-images.githubusercontent.com/14002834/148842737-5f8fc15c-5425-45d2-8a5f-768786d131cd.png)
