### ISSUE TITLE
Suggestion:  Please consider adding Config Option for 1.13 light levels in Water

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#65]
Love the mod, but one of the more recent updates changed the light levels for water.

Although it makes it in-line with 1.13 light levels, I would REALLY appreciate a config option for this!  The modpack I use is far better off with the darker levels of water of 1.12.2.

I just want the swimming mechanic without the water-brightening mechanic, if possible.

**Comment by embeddedt** [comment]
I've added a config option in 1.8.0. Please note that it will *not* re-light your world after you change it, so you will need to use an external tool/another mod/regenerate the world for the light levels to be updated. Newly generated chunks will have the appropriate light level.

**Comment by ghost** [comment]
Thank you so much!
