### ISSUE TITLE
[Suggestion] Option to toggle 'crawling' mode? Like if you press/hold a button... you'll enter 'crawling' mode.

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/fivefeetsmall#68]
I noticed that you can fit into 1x1 block gaps if something were to force you to enter 'crawling' mode. You can also sorta do this if you time a elytra glide near some 1x1 block gaps.

Would it be outside the scope to enable a use of a custom button so you can enter/leave crawling mode? I have some ideas with this and one use of this is being able to fit inside 1x1 gaps just o do some pipework for like... RF wiring, redstone wiring, etc.

This option could be toggle-able if it's deemed too powerful, or something.

**Comment by embeddedt** [comment]
It's a good suggestion! I actually have a request for this already (#35), just haven't found a good way of implementing it yet.
