### ISSUE TITLE
Catserver open service a moment to report an error

### ISSUE THREAD

**Issue by Lonelyxiya** [Fuzss/fivefeetsmall#69]
Catserver run when there is an unknown problem as follows This is the server log provided to you
[latest.log](https://github.com/Fuzss/aquaacrobatics/files/7917917/latest.log)
[debug.log](https://github.com/Fuzss/aquaacrobatics/files/7917918/debug.log)
.

**Comment by mxnmnm** [comment]
Same crash as well: https://gist.github.com/mxnmnm/d10a365b027c481a0ff65a14de0cc8a9

**Comment by embeddedt** [comment]
Thanks; that should be fixed in 1.9.1.
