### ISSUE TITLE
hitbox issue when flying

### ISSUE THREAD

**Issue by touhouzun** [Fuzss/fivefeetsmall#7]
with both aqua acrobatics and wings installed
![2020-12-28_20 50 36](https://user-images.githubusercontent.com/31458903/103250829-cd28b180-49b0-11eb-8e74-3fa7195a3ce1.png)
with only wings
![2020-12-28_21 01 03](https://user-images.githubusercontent.com/31458903/103250832-d285fc00-49b0-11eb-9d51-3acb96a91d9e.png)
Swimming hitbox is correctly one block high.

**Comment by Fuzss** [comment]
Fixed in 87c656e and released on CurseForge as v1.1.4.
