### ISSUE TITLE
Biomes o Plenty water color issue with latest 1.9.2

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#70]
![2022-02-02_15 35 04](https://user-images.githubusercontent.com/71896090/152311945-b260abbc-236a-40e5-9c38-f7bdded42115.png)
**Wetland** has very Purple water.

<img src="https://user-images.githubusercontent.com/71896090/143823597-b2d99478-d6f0-46bc-b4c9-cb3483f58efa.png" height="100">

![2022-02-02_10 39 45](https://user-images.githubusercontent.com/71896090/152312003-966d46bc-e735-4f13-ab1a-5722399e0b48.png)
**Mangrove** water is extra teal, which has a harsh contrast with the default water color of the roots when used with Dynamic Trees BoP.

**Comment by embeddedt** [comment]
The wetlands color was taken directly from BOP 1.16; here is a screenshot from that version. It looks like the same amount of purple to me (the biome changes to another one away from the shore, hence the lack of purple there).

![2022-02-03_23 48 38](https://user-images.githubusercontent.com/42941056/152449078-4ae17902-daa6-4936-89ea-1d5ce4c4c0b0.png)

I will see what I can do about the color mismatch for the Dynamic Trees roots.

**Comment by embeddedt** [comment]
I sent a PR to Dynamic Trees, as the issue is technically within their mod. Hopefully they accept it, if not I will have to patch their mod at runtime.

**Comment by ghost** [comment]
Hi, in latest 1.11.0, new error when `"New Water=true"`:
![image](https://user-images.githubusercontent.com/71896090/153649368-00f7afdc-5b21-48d2-a6a5-21ccd00ffcac.png)

when `"New Water=false"`:

![image](https://user-images.githubusercontent.com/71896090/153650731-ba275bd1-5ffc-41cf-b86a-79fcf8c9ad62.png)

**Comment by embeddedt** [comment]
I made some more changes to texture handling in 1.11.0 as I have gotten a
number of requests to allow using the old textures. Apparently, this new
approach is not as widely compatible as I had hoped. I'll look into this
but it may take a couple of days.

**Comment by embeddedt** [comment]
I realized that this may be caused by the lack of the texture fix in https://github.com/DynamicTreesTeam/DynamicTrees/pull/669; give 1.11.2 a try.

**Comment by embeddedt** [comment]
This should all be fixed if you use the latest version of Aqua Acrobatics.
