### ISSUE TITLE
1.11.0 Crash on startup

### ISSUE THREAD

**Issue by brisingraerowing** [Fuzss/fivefeetsmall#72]
[Crash Log](https://gist.github.com/brisingraerowing/a59e004e2c29a93cf02f06f8077ab273)

**Comment by embeddedt** [comment]
I can't reproduce this, but I believe you, and I see how it might happen. Does this build fix it?

[aqua.zip](https://github.com/Fuzss/aquaacrobatics/files/8045591/aqua.zip)

**Comment by dazadazu** [comment]
> I can't reproduce this, but I believe you, and I see how it might happen. Does this build fix it?
> 
> [aqua.zip](https://github.com/Fuzss/aquaacrobatics/files/8045591/aqua.zip)

That fixed it for me. Mine was crashing with the mod "Had enough items" Which is the fork of the original which supposedly improves load times.

**Comment by brisingraerowing** [comment]
I'll have to test that later.
