### ISSUE TITLE
[Bug] [1.11.2] [Mixinbooter 4.1] Crash/ Softlock when other player is performing the eating animation

### ISSUE THREAD

**Issue by Vapaman** [Fuzss/fivefeetsmall#74]
Steps to reproduce:

1) Enable eating animation
2) Join multiplayer
3) Witness someone perform the animation
4) Crash/softlock should occur

Modlist:
.mixinbooter-4.1
AquaAcrobatics-1.11.2
forge 14.23.5.2860

**Comment by embeddedt** [comment]
This will be fixed in 1.11.3.
