### ISSUE TITLE
Odd cauldron textures.

### ISSUE THREAD

**Issue by Carvercarver1** [Fuzss/fivefeetsmall#76]
Not exactly sure what causes that, but cauldron water texture with "new water" is doing that for some reason. Using newest AA. 
 I removed most mods related to the water changes and it still seemed to be there, but I did not remove fluidlogged as it seems that there already was a fix so I haven't checked that. 
Can you investigate the issue please? Perhaps I needed to regen config, since I did not redo it for quite some time?
![2022-02-19_01 22 00](https://user-images.githubusercontent.com/48799631/154779395-c2a46172-23bb-4f77-8c83-67628c9da5e6.png)

**Comment by embeddedt** [comment]
Which version is this? I'm not able to reproduce with 1.11.6.

**Comment by Carvercarver1** [comment]
1.11.4?

**Comment by Carvercarver1** [comment]
I will test with the newest one, I just don't remember anything like that in the changelog

**Comment by Carvercarver1** [comment]
After hitting it with more hammers, it now works correctly. It seems some things were out of life for both client and mod version. Now fixed. 

If similar issues occur, tell them to update or that newer updates have a fix for it.
