### ISSUE TITLE
When the "New Water" config is false, water fog turns pure white

### ISSUE THREAD

**Issue by juraj-hrivnak** [Fuzss/fivefeetsmall#77]
### The Issue
Water fog is pure white when `"New Water"=false` and `"New Water Fog"=true`
![2022-02-26_14 05 50](https://user-images.githubusercontent.com/71150936/155844465-c6acd445-0bf9-4067-98f7-75f5735551fc.png)

I wanted to use the old water rendering but with the new fog rendering enabled. But then the water fog doesn't seem to be right.

**Comment by embeddedt** [comment]
Hmm.. I can't reproduce this in an environment with only Aqua Acrobatics and BOP installed, in a coral reef biome.

**Comment by juraj-hrivnak** [comment]
Sorry for the late reply. I have finally figured out why is this happening. It's not related to Aqua Acrobatics, though.
Sorry for the false report!
