### ISSUE TITLE
some little suggestions

### ISSUE THREAD

**Issue by touhouzun** [Fuzss/fivefeetsmall#8]
(1) "When the player is swimming he should have more speed and go where the crosshair is pointing, the rest of the mechanics are perfectely implemented.
Excellent mod."
by curseforge user jahirtrap, but I have the similar or same request too. Swimming should be more like modern minecraft versions if necessary.

- [x] (2) Would there be a chance to restore the old-school, less-buggy FiveFeetSmall? (Deleted)

(I must have been in a 'today's blindwatch'.)

Anyway, always have a nice day! :)

**Comment by Fuzss** [comment]
FiveFeetSmall is still available, the jars have simply been renamed. Just download v1.0.1 of Aqua Acrobatics.

**Comment by Fuzss** [comment]
Swimming movement has been properly added in 6b8cb21 which has just been released on CurseForge as v1.1.2.
