### ISSUE TITLE
[Question]Bubble column cannot affect ender pearl

### ISSUE THREAD

**Issue by TUsama** [Fuzss/fivefeetsmall#80]
In 1.16.5, if you throw an ender pearl to at least an 8-blocks depth Bubble column, the pearl's movement will be inverted and float up to the water surface. this could be very useful when you try to build some contraption. For now, the pearl after you throw acts like no bubble column, it just goes down directly. I wonder if this mod can port this feature back.

Thanks a lot for your work!

**Comment by embeddedt** [comment]
I've added a config option for this in 1.12.2 (mod version, not Minecraft version). However, there is a lot of weirdness in Minecraft 1.12 in terms of how entities desync between the server and client, and I found some other, vanilla issues in testing where the pearl would disappear server-side but still be visible on the client. I'm not sure if this will work 100% as you expect from 1.16.

**Comment by TUsama** [comment]
OMG thank you so much! This could be very useful actually.
