### ISSUE TITLE
Compatibility with Witchery Resurrected

### ISSUE THREAD

**Issue by DarianLStephens** [Fuzss/fivefeetsmall#81]
Witchery Resurrected has many of the same features of Witchery, including potions and transformations that can change your size.
With Aqua Acrobatics installed, the eye height remains constant regardless of transformations or potion effects.
You can also crawl in these new forms, despite it visually not matching up at all.
![2022-03-24_07 59 23](https://user-images.githubusercontent.com/15375876/159794758-2391e020-16b7-4db7-be89-e14a2988f244.png)
![2022-03-24_07 59 31](https://user-images.githubusercontent.com/15375876/159794766-ff538817-932f-443d-ba6b-f5819c1ab362.png)

![2022-03-24_07 59 54](https://user-images.githubusercontent.com/15375876/159794773-5baa1472-1c23-4bf5-9750-e70ad97d754c.png)
![2022-03-24_07 59 57](https://user-images.githubusercontent.com/15375876/159794775-1b1002aa-2570-449a-96a7-08024a582749.png)

**Comment by embeddedt** [comment]
Thanks for the report. Unfortunately, as the mod appears to be closed-source and not officially released, I am not able to provide reliable compatibility for it at this time.

**Comment by DarianLStephens** [comment]
Aww. That's fair, though.
Hopefully the next version will be an official release, given the plan is for that version to be the start of Beta.

They do have a decent API even now, with some other mods having support for its transformations. They seem very willing to answer questions in their Discord server, if you were interested in getting a head-start?

**Comment by embeddedt** [comment]
Compatibility will be available in 1.13.0. Thanks again to @Shazuli for this contribution.
