### ISSUE TITLE
Ticking entity crash with Biomes o' Plenty boats

### ISSUE THREAD

**Issue by juraj-hrivnak** [Fuzss/fivefeetsmall#84]
### The issue

Any bop boat crashes the game when placed.

### To reproduce

- Install `Aqua Acrobatics v1.13.0`, `Biomes O' Plenty v7.0.1`, `mixinbooter`.
- Place the boat.
- Crash :O

### Logs

[Latest log](https://gist.github.com/juraj-hrivnak/7be9da37741e0a0138846691d3a609ba)
[Crash repport](https://gist.github.com/juraj-hrivnak/9a339827065d22b3bcd877e73b4f9757)

**Comment by embeddedt** [comment]
Thanks for the report; this is fixed in ~~1.13.1~~ 1.13.2. For older versions of the mod you can work around the issue by disabling bubble columns.

**Comment by juraj-hrivnak** [comment]
Whoa, thank you for the quick fix!
