### ISSUE TITLE
When I load Aqua Acrobatics it crashes

### ISSUE THREAD

**Issue by ainlzj** [Fuzss/fivefeetsmall#86]
When I load Aqua Acrobatics it crashes

Prefix, I also added MixinBootstrap
[minecraft-exported-logs-2022-05-04T23-29-13.log](https://github.com/Fuzss/aquaacrobatics/files/8621849/minecraft-exported-logs-2022-05-04T23-29-13.log)

**Comment by embeddedt** [comment]
Aqua Acrobatics is not compatible with Thicc Entities as mentioned on the [mod page](https://www.curseforge.com/minecraft/mc-mods/aqua-acrobatics).

**Comment by ainlzj** [comment]
Is there a way you can fix it?

**Comment by embeddedt** [comment]
I haven't tested it but you should be able to use [Entifier](https://www.curseforge.com/minecraft/mc-mods/entifier) instead; this is mentioned on the mod page.

**Comment by ainlzj** [comment]
I added the module on the basis of the integration package of others. I deleted the original file. I am afraid that the integration package data will be lost, but the module has been successfully activated. Thank you very much.

**Comment by embeddedt** [comment]
Glad you could fix it!
