### ISSUE TITLE
Incompatible with OptiFine G5

### ISSUE THREAD

**Issue by MistakingManx** [Fuzss/fivefeetsmall#88]
All `minecraft:water` blocks are just grey and white for some reason, but the water fog is blue like it should be.

I've changed no settings, would a resource pack fix it?

![image](https://user-images.githubusercontent.com/28667267/167312445-81cdb2d0-d805-4a44-b946-d9eb6eb9d5c3.png)

**Comment by embeddedt** [comment]
What other related mods do you have installed (e.g. OptiFine or other invasive mods that might tweak the renderer)?

**Comment by MistakingManx** [comment]
I have a lot of mods like Security Craft and BoP, but other than that I don't notice water differences.

I do use OptiFine though.

**Comment by embeddedt** [comment]
It's likely that one of your other mods overwrites the water renderer and prevents Aqua Acrobatics' coloring mechanism from working correctly. You would have to try bisecting to find the issue (i.e. remove half the mods and see if the problem goes away, if so, the problematic mod is in that half and repeat).

Aqua Acrobatics should be compatible with OptiFine but it's worth one try without just to be sure.

**Comment by MistakingManx** [comment]
Would the **DISABLE** button do the same thing as removing the mod? It takes ages to start

**Comment by embeddedt** [comment]
No, unfortunately you have to restart each time, there's no other way. It's an extremely painful process, I know. I'm actually doing it in the background on a 1.7 pack right now to track down a memory leak. You can speed it up a bit if you strategically pick the mods to remove (e.g. remove anything to do with water first).

**Comment by embeddedt** [comment]
Or, if you just want the swimming, you can turn off the water coloring and fog in the config and restart the game, and it should be back to 1.12 colors.

**Comment by MistakingManx** [comment]
The issue is with Optifine 1.12.2 G5

**Comment by embeddedt** [comment]
Interesting, I'll investigate that then. It worked with OptiFine the last time I checked...

**Comment by MistakingManx** [comment]
It's likely one of the options I have turned on or off, I'm going through them now.

**Comment by MistakingManx** [comment]
When changing settings, I can see the water be blue for a split second when it's reloading chunks

**Comment by MistakingManx** [comment]
I spent a long time checking through every setting and nothing fixed it except adding a shaders pack, so is it truly incompatible with optifine or just an issue I'm having by myself, like what normally happens to me?

**Comment by embeddedt** [comment]
Sorry, I should have sent a comment when renaming the issue. It is in fact incompatible with OptiFine again, which is a bug that I will fix when I have a chance. I don't normally play with OptiFine so I haven't noticed it in testing.

**Comment by ElLiox** [comment]
I have the same problem with Optifine HD U G5 (the last version) and BiomesOPlenty 7.0.1.2445 (the last version)
But is only happening in the last version (AquaAcrobatics 1.13.3)
Before that version, everything works fine
Here is a comparison: https://imgur.com/a/wgXqsW7

**Comment by MistakingManx** [comment]
I've covered up the issue for now by using a shader pack

**Comment by embeddedt** [comment]
This should be fixed in 1.13.4, which has been uploaded to CurseForge and is just waiting for approval.

**Comment by MistakingManx** [comment]
> This should be fixed in 1.13.4, which has been uploaded to CurseForge and is just waiting for approval.

While I'm here talking to someone at least decently experienced with 1.12.2, how the heck do I get custom music to load in a resource pack!? I can't get an updated version of extreme weather, so I'm trying to bring all the newer features back to 1.12.2 including the music, but for some reason it doesn't look like it's even loading my `sounds` from the Resource Pack

Someone online says that it can't be done for 1.12.2, so that means I have to learn how to do super basic modding for a very out-dated client

**Comment by embeddedt** [comment]
I would like to be of more help, but unfortunately I haven't done much with sounds in resource packs.

**Comment by MistakingManx** [comment]
Could you friend me on Discord, `MistakingManx#5555`? I have questions unrelated to your mod, but I still would greatly like to ask if you'd let me!

**Comment by embeddedt** [comment]
I'm involved with a modding group called Cleanroom which has a lot of 1.12 experts. Chances are one of us can help you out, the Discord invite is here: https://discord.gg/f2K4aSpG4F

**Comment by embeddedt** [comment]
Closing as the original issue should be resolved now.
