### ISSUE TITLE
[Compat] Eye height not changing based on ArtemisLib size

### ISSUE THREAD

**Issue by kappa-maintainer** [Fuzss/fivefeetsmall#89]
![2022-05-13_00 38 06](https://user-images.githubusercontent.com/11038263/168127337-9e33bf37-19c7-4fbf-bc2b-5dbac4a8b0a3.png)
ArtemisLib's eye height logic is located at com.artemis.artemislib.util.AttachAttributes#onPlayerTick

**Comment by kappa-maintainer** [comment]
I made a patch mod to fix this and many other incompatibilities. It seems the eye height factor should multiple like [this](https://github.com/kappa-maintainer/CPMC/blob/898b002b03ae411e840bf10927b54f1b525ce992/src/main/java/gkappa/cpmc/mixin/MixinEntityPlayer.java#L25) to get the correct eye height

**Comment by embeddedt** [comment]
I'd prefer to have the compatibility fix within Aqua Acrobatics to avoid breakage and so an external mod is not needed, if you give permission. Your fix seems to make sense although I don't understand where the multiplication by 3 comes from?

**Comment by kappa-maintainer** [comment]
Yes, double mixin is always not a good idea. As for the factor 3, see [here](https://github.com/Fuzss/aquaacrobatics/blob/48ba35fa75bff5ea725ab5b631eafe1af9b5f034/src/main/java/com/fuzs/aquaacrobatics/integration/artemislib/ArtemisLibIntegration.java#L18). My mod patched ArtemisLib to make it use CPM size but somehow made it multiple 1/3 twice here, so I have to revert it.

**Comment by embeddedt** [comment]
@kappa-maintainer Does https://github.com/Fuzss/aquaacrobatics/commit/e3bfb9f9fafc872eead8806d81fb4f26a7234c86 work for your mod? I haven't released it yet in case it needs further tweaking.

**Comment by kappa-maintainer** [comment]
I will test this

**Comment by kappa-maintainer** [comment]
It works perfectly under many mod combinations, I should remove my double mixin now
How the 1/3 got multiplied twice is still a mystery though

**Comment by embeddedt** [comment]
Great! Released as 1.14.1.
