### ISSUE TITLE
Suggestion - Add the new climbing as an option

### ISSUE THREAD

**Issue by MistakingManx** [Fuzss/fivefeetsmall#91]
Something (i think) was introduced in 1.13 was the ability to hold space to climb vines and ladders, since you implemented crawling (i assume that it's required for swimming or something like that), is it possible to implement the new climbing method as an option too?

I use it a lot more than I thought I did.

**Comment by embeddedt** [comment]
Implemented in 1.14.0. You can enable it with the `New Climbing Behavior` option.
