### ISSUE TITLE
Mo Bends Bug

### ISSUE THREAD

**Issue by SenZ01** [Fuzss/fivefeetsmall#93]
**Good evening, i've run into a visual conflic with the Mob bends mod which causes swimming and crawling to look like this in F5**

![image](https://user-images.githubusercontent.com/74424517/171665812-457a62d2-222c-4058-9cf0-5d29c2e0d85a.png)
![image](https://user-images.githubusercontent.com/74424517/171665860-5abe3463-4ba5-450d-a4bf-2d0d910569a2.png)

**I am running a modpack on 1.12, at first i didn't know what could have caused this so removed all my mods and put them back in each time only 50% of the mods to troubleshoot until mobends was the only one left, i have not yet tested to see if it's another mod that conflicts with mobends and aqua acrobatics but i will do some more testing later this evening.**

### Mod Versions;
**AquaAcrobatics-1.14.1**
**MoBends_1.12.2-1.1.0-28.09.21**

**Comment by embeddedt** [comment]
There is currently a known incompatibility with MoBends, as reported in #75. At the moment, I have not had time or interest to investigate it further.

Thanks for the report!
