### ISSUE TITLE
Bubble Celoms Backport mod causes water to become bugged.

### ISSUE THREAD

**Issue by MagmaSlime123** [Fuzss/fivefeetsmall#95]
Title.

With Aqua Acrobatics, water becomes bugged if a soulsand/magma bubble column is created. Other mods are being
used, but I can confirm this isn't caused by them. I don't have anything related to water, besides these 2 mods. Or, it
may be worth just backporting and putting this into AA itself.

Link: https://www.curseforge.com/minecraft/mc-mods/bubble-column-elevator-backport

![2022-06-07_16 39 14](https://user-images.githubusercontent.com/51277766/172494883-5a3acc01-b340-410e-a59d-d6a56b5a9622.png)

**Comment by embeddedt** [comment]
Aqua Acrobatics has bubble columns - check the config file. 🙂

**Comment by MagmaSlime123** [comment]
Ah, didn't know that, my bad.

Is Sea Grass even a thing, btw?

![2022-06-07_19 14 20](https://user-images.githubusercontent.com/51277766/172510310-c22b5d06-bed3-4bfb-8474-ba43496029a7.png)

Those are BetterFoliage corals, btw.

![2022-06-07_19 14 35](https://user-images.githubusercontent.com/51277766/172510314-69a4e42f-b452-460c-8e45-483f433ae1ef.png)

**Comment by embeddedt** [comment]
Yes, but not on the release branch. I have a second branch with most of the remaining 1.13 features like coral (no worldgen), drowneds, kelp, and shipwrecks. That config is just a placebo for now.

**Comment by MagmaSlime123** [comment]
Ah, hopefully this and those working features are added.
