### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by lartts** [Fuzss/fivefeetsmall#98]
Crash Log:
https://pastebin.com/eHE4CU2n

Only happens when Aqua Acrobatics is installed

**Comment by embeddedt** [comment]
It looks like you have TickCentral installed. Please apply [this workaround](https://github.com/Fuzss/aquaacrobatics/issues/44#issuecomment-1002681548) as mentioned near the bottom of the mod page; that should solve your issue. :slightly_smiling_face: However, you will unfortunately not be able to use bubble columns.
